module.exports = {
  version: '0.2',
  language: 'en',
  words: [
    // general
    'jscoverage',
    'hdwallet',
    // projects
    'emretepedev',
  ],
  ignoreWords: [],
  ignorePaths: ['.gitignore', 'yarn.lock', 'tags*'],
  allowCompoundWords: true,
  dictionaries: [
    'javascript',
    'typescript',
    'npm',
    'node',
    'filetypes',
    'softwareTerms',
    'dockerfile',
    'markdown',
    'xml',
    'yaml',
    'bash',
    'powershell',
    'cpp',
    'c',
    'json',
    'jsonc',
    'plaintext',
    'aws',
    'public-licenses',
    'cryptocurrencies',
    'companies',
    'misc',
    'en-gb',
    'lorem-ipsum',
  ],
};
